[package]
name = "rspark"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-once-cell = "0.5.3"
mongodb = "2.7.1"
once_cell = "1.18.0"
rspark-derive = {version = "0.0.1" , path = "derive"}
serde = { version = "1.0.192", features = ["derive"] }

[dev-dependencies]
tokio = "1.34.0"

[workspace]
members = [
    "derive"
]
