[package]
name = "rspark"
version = "0.1.0"
edition = "2021"
description = "RSpark is an open-source, fast, and memory-efficient Object-Relational Mapping (ORM) library for MongoDB written in Rust. It allows seamless integration between Rust structs and MongoDB collections by automatically converting structs to models. "
repository = "https://github.com/RSaprk/ORM.git"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.74"
futures = "0.3.29"
mongodb = "2.7.1"
once_cell = "1.18.0"
quote = "1.0.33"
rspark-derive = {version = "0.1.0" , path = "derive"}
serde = { version = "1.0.192", features = ["derive"] }
tokio = { version = "1.34.0" , features = ["rt" , "macros"] }
[dev-dependencies]

[workspace]
members = [
    "derive",
]
